build:
  image: golang:1.6.1
  environment:
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get github.com/kardianos/govendor
    - govendor sync
    - cd stompd
    - go build
